[package]
edition = "2021"
name = "libmw"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = {version = "1.0"}
